// Code generated by MockGen. DO NOT EDIT.
// Source: go-ddd/domain/geolocation (interfaces: Repository)

// Package mock is a generated GoMock package.
package mock

import (
	geolocation "go-ddd/domain/geolocation"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetLocationDataFromIP mocks base method.
func (m *MockRepository) GetLocationDataFromIP(arg0 string) ([]geolocation.GeoData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocationDataFromIP", arg0)
	ret0, _ := ret[0].([]geolocation.GeoData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocationDataFromIP indicates an expected call of GetLocationDataFromIP.
func (mr *MockRepositoryMockRecorder) GetLocationDataFromIP(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocationDataFromIP", reflect.TypeOf((*MockRepository)(nil).GetLocationDataFromIP), arg0)
}

// Upsert mocks base method.
func (m *MockRepository) Upsert(arg0 geolocation.GeoData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRepositoryMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRepository)(nil).Upsert), arg0)
}
